name: serpapi-ruby
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.1.0','head'] # test only recommend Ruby version (and stable version on the gitaction server)
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: install dependencies
        run: bundle install
      - name: lint
        run: bundle exec rake lint
      - name: tests
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: bundle exec rake test
      - name: out of box testing
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: bundle exec rake oobt
