name: serpapi-ruby
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1.0','head'] # test only recommend Ruby version (and stable version on the gitaction server)
     #   ruby-version: ['2.7.4','3.1.0','head']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: lint
        run: bundle exec rake lint
      - name: tests
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: bundle exec rake test
      - name: oobt
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: bundle exec rake oobt
